---
- name: restart jenkins
  service: name=jenkins state=restarted

- name: configure default users
  template:
    src: basic-security.groovy.j2
    dest: "/var/lib/jenkins/init.groovy.d/basic-security.groovy"
    owner: "jenkins"
    group: "jenkins"
    mode: 0775
  register: jenkins_users_config
